### PR TITLE
fixed mushra 100 rating error

### PR DESCRIPTION
**Pull request by evelyndjwilliams**

### CODE REVIEW

**Comment by jacobjwebber** [comment]
Thanks @evelyndjwilliams !
Perhaps we can pretty print this JSON file so that patch changes are more obvious? Can you see any problems with me doing that?

@dan-wells Does this look ok to you or would you like to patch testmaker.py

**Comment by dan-wells** [comment]
Looks good to me, and works as expected on Qualtrics wrt. rating validation.

There's a hard limit here for 12 test stimuli per MUSHRA panel, but this is consistent with the original recommendation document and should be adequate for anybody being sensible. The only additional benefit of doing things dynamically in testmaker.py might be to reduce complexity in the template (+1 for pretty-printing that!)

**Comment by jacobjwebber** [comment]
uhhh i have done that with the pretty printing but don't have push access to @evelyndjwilliams fork repo so can't commit to this PR directly

I have made the change so could you pull from my repo and push to your main (which should automatically update the pr). Something like

git remote add jacob git@github.com:jacobjwebber/qualtreats.git
git pull jacob main
git push origin main

should work

I like the idea of a hard stimuli limit if that what is consistent with the MUSHRA standard. @dan-wells If your changes make things in testmaker.py neater it would be a shame to waste that though... perhaps you could do another pr?

Thank you both 😊

**Comment by jacobjwebber** [comment]
i have no idea how the mushra code works btw! 😞

**Comment by dan-wells** [comment]
> @dan-wells If your changes make things in testmaker.py neater it would be a shame to waste that though... perhaps you could do another pr?

sure, I can look at it again and turn it from a quick fix into a more general approach

**Comment by jacobjwebber** [comment]
OK gonna merge this 🤞

Guess we should add tests at some  point but tricky to do for this...

**Pull request merged**
